// 기술 스택 상수 정의
export const TECH_STACKS = [
  { id: 1, name: 'TypeScript' },
  { id: 2, name: 'JavaScript' },
  { id: 3, name: 'C' },
  { id: 4, name: 'Python' },
  { id: 5, name: 'Java' },
  { id: 6, name: 'React' },
  { id: 7, name: 'Vue.js' },
  { id: 8, name: 'Angular' },
  { id: 9, name: 'Node.js' },
  { id: 10, name: 'Spring' },
  { id: 11, name: 'Django' },
  { id: 12, name: 'Flutter' },
  { id: 13, name: 'React Native' },
  { id: 14, name: 'Next.js' },
  { id: 15, name: 'Express' },
  { id: 16, name: 'MySQL' },
  { id: 17, name: 'MongoDB' },
  { id: 18, name: 'PostgreSQL' },
  { id: 19, name: 'Docker' },
  { id: 20, name: 'Kubernetes' },
  { id: 21, name: 'AWS' },
  { id: 22, name: 'Git' },
  { id: 23, name: 'Figma' },
  { id: 24, name: 'Photoshop' },
];
